import {useState} from 'react';
import {current,customerRank,portfolioRank,priceRanges} from '../data/season';
import type {Rank} from '../data/season';
import {VisualCard} from '../components/VisualCard';
import {ScanCombo,RangeCombo} from '../visuals/Combo';
import {fmt} from '../lib/format';
export function ComboPage(){const [active,setActive]=useState(new Set(['gpPct','soldRetail','retailGp','sellThru']));const [selected,setSelected]=useState<string|null>(null);const buttons=[['gpPct','Retail GP %'],['soldRetail','Sold Retail $'],['retailGp','Retail Profit $'],['sellThru','Unit Sell Through %']];const toggle=(key:string)=>setActive(old=>{const next=new Set(old);if(next.has(key))next.delete(key);else next.add(key);return next});return <div onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="page-heading"><div><span className="eyebrow">PERFORMANCE BY SUBCATEGORY</span><h1>Scan Combo Graph</h1></div></div><div className="segments">{buttons.map(([key,label])=><button className={active.has(key)?'active':''} key={key} onClick={()=>toggle(key)}>{label}</button>)}</div><VisualCard title="Retail, profit and sell-through"><ScanCombo rows={current} active={active} selected={selected} onSelect={setSelected}/></VisualCard></div>}
export function PricePage(){return <div><div className="page-heading"><div><span className="eyebrow">PRICE ARCHITECTURE</span><h1>Scan Price Range</h1></div></div><VisualCard title="Price Range Matrix"><div className="table-wrap"><table><thead><tr><th>Range</th><th>Sold Retail</th><th>Margin</th><th>Profit</th><th>Sell-Thru</th><th>% Total</th></tr></thead><tbody>{priceRanges.map(r=><tr key={r.range}><td>{r.range}</td><td>{fmt.money(r.soldRetail)}</td><td>{fmt.pct(r.margin,false)}</td><td>{fmt.money(r.profit)}</td><td>{fmt.pct(r.sellThru,false)}</td><td>{fmt.pct(r.share,false)}</td></tr>)}</tbody></table></div></VisualCard><div className="projection-grid"><VisualCard title="Customer"><RangeCombo data={priceRanges} dataKey="sellThru"/></VisualCard><VisualCard title="Portfolio"><RangeCombo data={priceRanges} dataKey="portfolioSellThru"/></VisualCard></div></div>}
export function TopPage(){const [hover,setHover]=useState<string|null>(null);return <div><div className="page-heading"><div><span className="eyebrow">ITEM BENCHMARK</span><h1>Top 10 Percent</h1></div></div><VisualCard title="Customer"><Ranks rows={customerRank} hover={hover} set={setHover}/></VisualCard><VisualCard title="Far East Brokers"><Ranks rows={portfolioRank} hover={hover} set={setHover}/></VisualCard></div>}
function Ranks({rows,hover,set}:{rows:Rank[];hover:string|null;set:(s:string|null)=>void}){return <div className="ranks">{rows.map((r,i)=><div className={`rank ${hover&&hover!==r.itemNo?'dim':''}`} key={r.itemNo} onMouseEnter={()=>set(r.itemNo)} onMouseLeave={()=>set(null)}><span>{i+1}</span><label>{r.itemNo} · {r.name}</label><div className="bar"><i style={{width:`${r.value??0}%`}}/></div><strong>{r.value===null?'':`${r.value} %`}</strong></div>)}</div>}
