import {Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {reconstructWeekly,weeklySpecs} from '../lib/weekly';
import {VisualCard} from '../components/VisualCard';

const colors=['#118DFF','#12239E','#E66C37','#6B007B','#E044A7','#744EC2','#D9B300','#D64550','#26BDFB','#32A887'];

export function WeeklyPage(){
  const data=reconstructWeekly();
  return <div><div className="coverage-alert"><strong>Partial coverage.</strong> The curve shapes were reconstructed with a normalized logistic function. Only the final percentage in each table row and the last point in each series are observed data from the recording.</div><div className="page-heading"><div><span className="eyebrow">DECLARED RECONSTRUCTION</span><h1>Scan by Week</h1></div></div><VisualCard title="Weekly cumulative sell-through · Jul 06–Oct 19"><div className="weekly-layout"><div className="weekly-matrix"><table><thead><tr><th>Category</th><th>Subcategory</th><th>Sell Through %</th></tr></thead><tbody>{weeklySpecs.map((spec,index)=><tr key={spec.sub}><td>{index===0?<span className="weekly-category">⊟ Halloween</span>:''}</td><td><i style={{backgroundColor:colors[index]}}/>{spec.sub}</td><td><strong>{spec.final.toFixed(1)} %</strong></td></tr>)}</tbody></table><p className="weekly-table-note">Final percentages are observed data.</p></div><div className="weekly-chart"><ResponsiveContainer width="100%" height={470}><LineChart data={data} margin={{top:12,right:18,left:0,bottom:8}}><XAxis dataKey="week"/><YAxis domain={[0,70]} tickFormatter={value=>`${value}%`}/><Tooltip formatter={(value:number,name:string)=>[`${value.toFixed(1)} %`,name]}/>{weeklySpecs.map((spec,index)=><Line key={spec.sub} dataKey={spec.sub} name={spec.sub} stroke={colors[index]} strokeWidth={2} strokeDasharray="5 4" dot={point=><circle key={`${spec.sub}${point.index}`} cx={point.cx} cy={point.cy} r={point.index===15?4:0} fill={colors[index]}/>} activeDot={{r:4}}/>)}</LineChart></ResponsiveContainer></div></div><p className="note">Declared reconstruction: dotted weekly paths are inferred; only the final filled markers and percentages in the table are observed.</p></VisualCard><VisualCard title="Data required to replace the reconstruction"><ul><li>Units sold by week and item.</li><li>First-sale date for each item.</li><li>Store distribution data to enable store-level analysis.</li></ul></VisualCard></div>;
}
